version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --init-file /usr/src/app/film.sql
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ./dbdata/film.sql:/usr/src/app/film.sql

  mysql_2:
    image: mysql
    restart: always
    command: --init-file /usr/src/app/detailsfilm.sql
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3308

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - mysql
      - mysql_2

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  pilote:
    build: ./pilote
    environment:
      NODE_ENV: development
      SERVICE_ADDRESS: pilote
    depends_on:
      - mysql
    ports:
      - 8080:8080

  bunga_object:
    build: ./bunga_object
    environment:
      NODE_ENV: development
    depends_on:
      - mysql
      - pilote
    ports:
      - 3000:3000

  bunga_details:
    build: ./bunga_details
    environment:
      NODE_ENV: development
    depends_on:
      - mysql_2
      - pilote
    ports:
      - 3006:3006

  # bunga_front_end:
  #   build: ./bunga_front_end
  #   environment:
  #     NODE_ENV: development
  #     SERVICE_ADDRESS: bunga_front_end
  #   depends_on:
  #     - mysql
  #     - mongo
  #     - pilote
  #   ports:
  #     - 4200:4200

  # bunga_location:
  #   build: ./bunga_location
  #   environment:
  #     NODE_ENV: development
  #     SERVICE_ADDRESS: bunga_location
  #   depends_on:
  #     - mysql
  #     - mongo
  #     - pilote
  #   ports:
  #     - 3002:3002

  #   build: ./bunga_utilisateur
  #   depends_on:
  #     - mysql
  #     - mongo
  #   ports:
  #     - 3004:3004
  #   volumes:
  #     - ./log:/root/.npm/_logs/
