openapi: 3.0.2
info:
  title: BungaTV
  description: 'Plateforme de location de film en ligne.'
  termsOfService: https://bunga.tv/terms/
  contact:
    email: api@bunga.tv
  license:
    name: NodeJS 2.0
    url: https://github.com/nodejs/node/blob/master/LICENSE
  version: 1.0.0
servers:
- url: https://bunga.tv/v1
tags:
- name: film
  description: Tout ce qui concerne un film
- name: location d'un film
  description: Tout ce qui concerne la location d'un film
- name: user
  description: Tout ce qui concerne un utilisateur
paths:
  /film:
    get:
      tags:
      - film
      summary: Liste de tout les films de la plateforme
      operationId: filmsGet
    post:
      tags:
      - film
      summary: Ajouter un film
      operationId: filmPost
      security:
        - user_auth:
          - write:addfilm
  /film/{idFilm}:
    get:
      tags:
      - film
      summary: Récuperer les informations du film
      operationId: filmGet
    put:
      tags:
      - film
      summary: Modifier un film
      operationId: filmPut
      security:
        - user_auth:
          - put:putfilm
    delete:
      tags:
      - film
      summary: Supprimer le film
      operationId: filmDelete
      security:
        - user_auth:
          - delete:deletefilm
  /film/details:
    get:
      tags:
      - film
      summary: Liste les détails de tout les films
      operationId: filmsDetailsGet
    post:
      tags:
      - film
      summary: Ajouter les détails de film
      operationId: filmsDetailPost
      security:
        - user_auth:
          - write:adddetailsfilm
  /film/details/{idFilm}:
    get:
      tags:
      - film
      summary: Récuperer tout les détails d'un film
      operationId: filmDetailGet
    put:
      tags:
      - film
      summary: Modifier tout les détails d'un film
      operationId: filmDetailPut
      security:
        - user_auth:
          - put:putdetailsfilm
    delete:
      tags:
      - film
      summary: Supprimer tout les détails d'un film
      operationId: filmDetailDelete
      security:
        - user_auth:
          - delete:deletedetailsfilm
  /location:
    get:
      tags:
      - location d'un film
      summary: Liste des films en location
      operationId: locationGet
    post:
      tags:
      - location d'un film
      summary: Ajouter un film en location
      operationId: locationPost
      security:
        - user_auth:
          - add:addlocation
  /location/{idLocationFilm}:
    get:
      tags:
      - location d'un film
      summary: Récupère les informations sur la location d'un film
      operationId: locationFilmGet
    put:
      tags:
      - location d'un film
      summary: Modifier la location d'un film
      operationId: locationFilmPut
      security:
        - user_auth:
          - put:putlocation
    delete:
      tags:
      - location d'un film
      summary: Supprimer la location d'un film
      operationId: locationFilmDelete
      security:
        - user_auth:
          - delete:deletelocation
  /user:
    post:
      tags:
      - user
      summary: Création d'un utilisateur
      description: Cette opération doit être effectué en étant connecté.
      operationId: createUser
  /user/login:
    get:
      tags:
      - user
      summary: Connexion d'un utilisateur
      operationId: loginUser
  /user/logout:
    get:
      tags:
      - user
      summary: Déconnexion de l'utilisateur actuellement connecté
      operationId: logoutUser
      security:
        - user_auth:
          - write:logout
  /user/{idUser}:
    get:
      tags:
      - user
      summary: Récuperer un utilisateur par son nom d'utilisateur
      operationId: getUser
    put:
      tags:
      - user
      summary: Mise à jour d'un utilisateur
      description: Cette opération doit être effectué en étant connecté à l'utilisateur qui est sujet à modification.
      operationId: updateUser
      security:
        - user_auth:
          - write:editprofile
    delete:
      tags:
      - user
      summary: Suppression d'un utilisateur
      description: Cette opération doit être effectué en étant connecté à l'utilisateur qui est sujet à suppression.
      operationId: deleteUser
      security:
        - user_auth:
          - delete:account
components:
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://bunga.tv/oauth/dialog
          scopes:
            write:addfilm: Ajouter un film
            put:putfilm: Modifier un film
            delete:deletefilm: Supprimer un film
            write:adddetailsfilm: Ajouter des détails d'un film
            put:putdetailsfilm: Modifier des details d'un film
            delete:deletedetailsfilm: Supprimer des détails d'un film
            write:addlocation: Ajouter un film en location
            put:putlocation: Modifier un film en location
            delete:deletelocation: Ajouter un film en location
            write:editprofile: Edition du profil
            delete:account: Suppression de son compte
            write:logout: Déconnexion du compte
