openapi: 3.0.2
info:
  title: Netstream
  description: 'Plateforme de vidéo à la demande sur des séries et films avec des spécificités sociales.'
  termsOfService: https://netstream.net/terms/
  contact:
    email: api@netstream.net
  license:
    name: NodeJS 2.0
    url: https://github.com/nodejs/node/blob/master/LICENSE
  version: 1.0.0
servers:
- url: https://netstream.net/v1
tags:
- name: series
  description: Tout ce qui concerne une série
- name: user
  description: Tout ce qui concerne un utilisateur
- name: favorite
  description: Tout ce qui concerne les favoris, les moments favoris et les commentaires
- name: played
  description: Tout ce qui concerne les séries vues et en cours de visionnage d'un utilisateur
paths:
  /series:
    get:
      tags:
      - series
      summary: Liste de toute les séries de la plateforme
      operationId: seriesGet
  /series/{serie}:
    get:
      tags:
      - series
      summary: Récuperer les informations d'une série par le nom saisie
      operationId: serieGet
  /series/{serie}/seasons:
    get:
      tags:
      - series
      summary: Récuperer la liste des saisons de la série saisie
      operationId: serieSeasonsGet
  /series/{serie}/seasons/{season}:
    get:
      tags:
      - series
      summary: Récuperer la liste des épisodes de la saison et de la série saisie
      operationId: serieSeasonEpisodesGet
  /series/suggest:
    post:
      tags:
      - series
      summary: Un utilisateur peut proposer d'ajouter une série au catalogue
      description: Cette opération doit être effectué en étant connecté.
      operationId: seriesSuggest
      security:
        - user_auth:
          - write:seriesuggest
          - read:readsuggestion
  /favorite:
    get:
      tags:
      - favorite
      summary: Affichage de tout les favoris de l'utilisateur connecté.
      operationId: favoriteGet
      security:
        - user_auth:
          - read:favoritelist
  /favorite/{serie}:
    post:
      tags:
      - favorite
      summary: "Ajout d'une série aux favoris de l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteAdd
      security:
        - user_auth:
          - read:favoritelist
          - write:favoriteadd
    put:
      tags:
      - favorite
      summary: "Modification d'une séries des favoris de l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteEdit
      security:
        - user_auth:
          - write:editprofile
    delete:
      tags:
      - favorite
      summary: "Suppression d'une série des favoris de l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteDelete
      security:
        - user_auth:
          - delete:favorite
  /favorite/moment:
    get:
      tags:
      - favorite
      summary: "Affichage d'un moment favoris des utilisateurs"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteMomentGet
      security:
        - user_auth:
          - read:momentlist
    post:
      tags:
      - favorite
      summary: "Ajout d'un moment favoris de l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteMomentAdd
      security:
        - user_auth:
          - read:momentlist
          - write:moment
    delete:
      tags:
      - favorite
      summary: "Suppression d'un moment favoris de l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteMomentDelete
      security:
        - user_auth:
          - read:momentlist
          - delete:moment
  /favorite/moment/comment:
    get:
      tags:
      - favorite
      summary: "Affichage des commentaires d'un moment favoris sur l'épisode actuel"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteMomentCommentsGet
      security:
        - user_auth:
          - read:commentlist
          - read:momentlist
    post:
      tags:
      - favorite
      summary: "Ajout d'un commentaire à un moment existant si le propriétaire du moment favoris est connecté"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteMomentCommentsAdd
      security:
        - user_auth:
          - read:commentlist
          - read:momentlist
          - write:comment
    delete:
      tags:
      - favorite
      summary: "Suppression d'un commentaire appartenant à l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: favoriteMomentCommentsDelete
      security:
        - user_auth:
          - read:commentlist
          - read:momentlist
          - delete:comment
  /played:
    get:
      tags:
      - played
      summary: Affichage de toute les séries en cours
      operationId: playedGet
      security:
        - user_auth:
          - read:playedlist
  /played/{serie}:
    post:
      tags:
      - played
      summary: "Ajout d'une série dans la liste des séries en cours de l'utilisateur"
      description: Cette opération doit être effectué en étant connecté.
      operationId: playedAdd
      security:
        - user_auth:
          - read:playedlist
          - write:playedadd
  /user:
    post:
      tags:
      - user
      summary: Création d'un utilisateur
      description: Cette opération doit être effectué en étant connecté.
      operationId: createUser
  /user/login:
    get:
      tags:
      - user
      summary: Connexion d'un utilisateur
      operationId: loginUser
  /user/logout:
    get:
      tags:
      - user
      summary: Déconnexion de l'utilisateur actuellement connecté
      operationId: logoutUser
      security:
        - user_auth:
          - write:logout
  /user/{username}:
    get:
      tags:
      - user
      summary: Récuperer un utilisateur par son nom d'utilisateur
      operationId: getUser
    put:
      tags:
      - user
      summary: Mise à jour d'un utilisateur
      description: Cette opération doit être effectué en étant connecté à l'utilisateur qui est sujet à modification.
      operationId: updateUser
      security:
        - user_auth:
          - write:editprofile
    delete:
      tags:
      - user
      summary: Suppression d'un utilisateur
      description: Cette opération doit être effectué en étant connecté à l'utilisateur qui est sujet à suppression.
      operationId: deleteUser
      security:
        - user_auth:
          - delete:account
components:
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://netstream.net/oauth/dialog
          scopes:
            write:seriesuggest: Proposé une série
            read:readsuggestion: Afficher sa proposition de série
            write:editprofile: Edition du profil
            delete:account: Suppression de son compte
            write:logout: Déconnexion du compte
            read:favoritelist : Liste des favoris d'un utilisateur
            write:favoriteadd : Ajout d'une série aux favoris de l'utilisateur
            delete:favorite : Suppression d'une série dans les favoris de l'utilisateur
            read:playedlist : Afficher la liste des séries en cours de visionnage de l'utilisateur
            write:playedadd : Ajouter une série en cours de visionnage à l'utilisateur
            read:momentlist : Afficher la liste des moments d'un utilisateur connecté sur l'épisode
            write:moment : Créer un moment favori sur l'épisode
            delete:moment : Supprimer un moment favori sur un épisode
            read:commentlist : Afficher la liste des commentaires sur un moment d'un épisode
            write:comment : Ajouter un commentaire à un moment favori d'un autre utilisateur connecté d'un épisode
            delete:comment : Supprimer un commentaire écrit par l'utilisateur